set(headers ${headers}
	src/C++/PCH.h
	src/C++/Hooks/EventHook.h
	src/C++/Papyrus/ActiveMagicEffect.h
	src/C++/Papyrus/Actor.h
	src/C++/Papyrus/ActorBase.h
	src/C++/Papyrus/Alias.h
	src/C++/Papyrus/ArmorAddon.h
	src/C++/Papyrus/Array.h
	src/C++/Papyrus/Book.h
	src/C++/Papyrus/Cell.h
	src/C++/Papyrus/Common.h
	src/C++/Papyrus/Debug.h
	src/C++/Papyrus/EffectShader.h
	src/C++/Papyrus/Enchantment.h
	src/C++/Papyrus/Events.h
	src/C++/Papyrus/ExtendedObjectTypes.h
	src/C++/Papyrus/FEC.h
	src/C++/Papyrus/Form.h
	src/C++/Papyrus/Furniture.h
	src/C++/Papyrus/Game.h
	src/C++/Papyrus/Hazard.h
	src/C++/Papyrus/Light.h
	src/C++/Papyrus/Location.h
	src/C++/Papyrus/MagicEffect.h
	src/C++/Papyrus/ObjectReference.h
	src/C++/Papyrus/Package.h
	src/C++/Papyrus/Potion.h
	src/C++/Papyrus/Projectile.h
	src/C++/Papyrus/Registration.h
	src/C++/Papyrus/Scroll.h
	src/C++/Papyrus/Sound.h
	src/C++/Papyrus/Spell.h
	src/C++/Papyrus/Strings.h
	src/C++/Papyrus/Utility.h
	src/C++/Papyrus/VisualEffect.h
	src/C++/Papyrus/Weather.h
	src/C++/Serialization/Events.h
	src/C++/Serialization/Manager.h
	src/C++/Serialization/Form/Base.h
	src/C++/Serialization/Form/Keywords.h
	src/C++/Serialization/Form/Perks.h
	src/C++/Util/ConditionParser.h
	src/C++/Util/Graphics.h
	src/C++/Util/Magic.h
)
