set(headers ${headers}
	include/Common.h
	include/Game/Cache.h
	include/Game/EventHandler.h
	include/Game/HookedEventHandler.h
	include/Game/Manager.h
	include/PCH.h
	include/Papyrus/Functions/ActiveMagicEffect/Events.h
	include/Papyrus/Functions/ActiveMagicEffect/Functions.h
	include/Papyrus/Functions/Actor.h
	include/Papyrus/Functions/ActorBase.h
	include/Papyrus/Functions/Alias/Events.h
	include/Papyrus/Functions/Alias/Functions.h
	include/Papyrus/Functions/ArmorAddon.h
	include/Papyrus/Functions/Array.h
	include/Papyrus/Functions/Book.h
	include/Papyrus/Functions/Cell.h
	include/Papyrus/Functions/Debug.h
	include/Papyrus/Functions/EffectShader.h
	include/Papyrus/Functions/Enchantment.h
	include/Papyrus/Functions/Faction.h
	include/Papyrus/Functions/Form/Events.h
	include/Papyrus/Functions/Form/Functions.h
	include/Papyrus/Functions/Furniture.h
	include/Papyrus/Functions/Game.h
	include/Papyrus/Functions/Hazard.h
	include/Papyrus/Functions/Light.h
	include/Papyrus/Functions/Location.h
	include/Papyrus/Functions/MagicEffect.h
	include/Papyrus/Functions/ObjectReference.h
	include/Papyrus/Functions/Package.h
	include/Papyrus/Functions/Potion.h
	include/Papyrus/Functions/Projectile.h
	include/Papyrus/Functions/Quest.h
	include/Papyrus/Functions/Scroll.h
	include/Papyrus/Functions/Sound.h
	include/Papyrus/Functions/Spell.h
	include/Papyrus/Functions/Strings.h
	include/Papyrus/Functions/UI.h
	include/Papyrus/Functions/Utility.h
	include/Papyrus/Functions/VisualEffect.h
	include/Papyrus/Functions/Weather.h
	include/Papyrus/Manager.h
	include/Papyrus/ObjectTypes.h
	include/Papyrus/Util/ConditionParser.h
	include/Papyrus/Util/Graphics.h
	include/Papyrus/Util/Magic.h
	include/Papyrus/Util/Script.h
	include/Serialization/EventHolder.h
	include/Serialization/Manager.h
	include/Serialization/Registration/DataMap.h
	include/Serialization/Registration/DataSet.h
	include/Serialization/Services.h
)
