set(headers ${headers}
	src/C++/Common.h
	src/C++/PCH.h
	src/C++/Game/Cache.h
	src/C++/Game/Events.h
	src/C++/Game/Manager.h
	src/C++/Papyrus/Manager.h
	src/C++/Papyrus/ObjectTypes.h
	src/C++/Papyrus/Functions/ActiveMagicEffect.h
	src/C++/Papyrus/Functions/Actor.h
	src/C++/Papyrus/Functions/ActorBase.h
	src/C++/Papyrus/Functions/Alias.h
	src/C++/Papyrus/Functions/ArmorAddon.h
	src/C++/Papyrus/Functions/Array.h
	src/C++/Papyrus/Functions/Book.h
	src/C++/Papyrus/Functions/Cell.h
	src/C++/Papyrus/Functions/Debug.h
	src/C++/Papyrus/Functions/EffectShader.h
	src/C++/Papyrus/Functions/Enchantment.h
	src/C++/Papyrus/Functions/FEC.h
	src/C++/Papyrus/Functions/Form.h
	src/C++/Papyrus/Functions/Furniture.h
	src/C++/Papyrus/Functions/Game.h
	src/C++/Papyrus/Functions/Hazard.h
	src/C++/Papyrus/Functions/Light.h
	src/C++/Papyrus/Functions/Location.h
	src/C++/Papyrus/Functions/MagicEffect.h
	src/C++/Papyrus/Functions/ObjectReference.h
	src/C++/Papyrus/Functions/Package.h
	src/C++/Papyrus/Functions/Potion.h
	src/C++/Papyrus/Functions/Projectile.h
	src/C++/Papyrus/Functions/Scroll.h
	src/C++/Papyrus/Functions/Sound.h
	src/C++/Papyrus/Functions/Spell.h
	src/C++/Papyrus/Functions/Strings.h
	src/C++/Papyrus/Functions/UI.h
	src/C++/Papyrus/Functions/Utility.h
	src/C++/Papyrus/Functions/VisualEffect.h
	src/C++/Papyrus/Functions/Weather.h
	src/C++/Papyrus/Util/ConditionParser.h
	src/C++/Papyrus/Util/Graphics.h
	src/C++/Papyrus/Util/Magic.h
	src/C++/Papyrus/Util/Script.h
	src/C++/Serialization/Events.h
	src/C++/Serialization/Manager.h
	src/C++/Serialization/Services.h
	src/C++/Serialization/Registration/DataMap.h
	src/C++/Serialization/Registration/DataSet.h
)
