name: Main

on:
  push:
    branches: '**'
    tags: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: github.repository_owner == 'powerof3'
    uses: powerof3/pack-skse-mod/.github/workflows/pack.yml@main-vs2022
    with:
      CMAKE_SE_CONFIG_PRESET: 'vs2022-se'
      CMAKE_SE_BUILD_PRESET: 'vs2022-se'
      CMAKE_AE_CONFIG_PRESET: 'vs2022-ae'
      CMAKE_AE_BUILD_PRESET: 'vs2022-ae'
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "powerofthree's Papyrus Extender"
      FOMOD_MOD_AUTHOR: "powerofthree"
      FOMOD_MOD_NEXUS_ID: "22854"
      FOMOD_SE_MIN_GAME_VERSION: '1.5'
      AE_353_BRANCH: master
      AE_353_COMMON_LIB_BRANCH: dev-1.6.1170
      FOMOD_AE353_PATH: 'AE1170/SKSE/Plugins'
      FOMOD_AE353_NAME:  'SSE/AE v1.6.1170 ("Anniversary/Special Edition")'
      FOMOD_AE353_DESCR: 'Select this if you are using Skyrim Anniversary Edition/Special Edition v1.6.1170 (Steam) or v1.6.1179 (GOG).'
      FOMOD_AE353_MIN_GAME_VERSION: '1.6.1170'
      FOMOD_AE_NAME: 'SSE/AE v1.7.104+ ("Anniversary/Special Edition")'
      FOMOD_AE_DESCR: 'Select this if you are using Skyrim Anniversary Edition/Special Edition v1.7.104 or higher (latest update).'
      FOMOD_AE_MIN_GAME_VERSION: '1.7'
      FOMOD_REQUIRED_INSTALLATION_DIR: "Papyrus"
      PUBLISH_ARCHIVE_TYPE: '7z'
